name: convo_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  # firebase_auth: ^3.0.1
  # firebase_core: ^1.4.0
  # firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  provider: ^6.0.1
  rive: ^0.7.33

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/others/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
