name: convo_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  enough_giphy_flutter: ^0.4.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.3.0
  fpdart: ^0.5.0
  get: ^4.6.5
  google_fonts: ^4.0.1
  google_sign_in: ^6.0.2
  image_picker: ^0.8.6+1
  provider: ^6.0.5
  rive: ^0.10.1
  shared_preferences: ^2.0.17
  stream_chat_flutter_core: ^5.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icon/
    - assets/riveAssets/
    - assets/images/
    - assets/others/
