// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LkpxFhpvfrpEbOYOq1yAHeJpT9xi88s',
    appId: '1:982105301472:web:9c66bd338f0d2d3cc08b85',
    messagingSenderId: '982105301472',
    projectId: 'convo-chat-fe48f',
    authDomain: 'convo-chat-fe48f.firebaseapp.com',
    storageBucket: 'convo-chat-fe48f.appspot.com',
    measurementId: 'G-X6GH85VVVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm2lXVgMXoXhwyJbDP8hbG3R7lH1-plvU',
    appId: '1:982105301472:android:c383c080a9af5569c08b85',
    messagingSenderId: '982105301472',
    projectId: 'convo-chat-fe48f',
    storageBucket: 'convo-chat-fe48f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXKYtJoOMGVS4NCX3rw6O6fIzd2caWro',
    appId: '1:982105301472:ios:63b3e868baf3f3cdc08b85',
    messagingSenderId: '982105301472',
    projectId: 'convo-chat-fe48f',
    storageBucket: 'convo-chat-fe48f.appspot.com',
    iosClientId: '982105301472-n82h2ipf0d1giklojkldhf8q9ro1i16i.apps.googleusercontent.com',
    iosBundleId: 'com.example.convoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXKYtJoOMGVS4NCX3rw6O6fIzd2caWro',
    appId: '1:982105301472:ios:63b3e868baf3f3cdc08b85',
    messagingSenderId: '982105301472',
    projectId: 'convo-chat-fe48f',
    storageBucket: 'convo-chat-fe48f.appspot.com',
    iosClientId: '982105301472-n82h2ipf0d1giklojkldhf8q9ro1i16i.apps.googleusercontent.com',
    iosBundleId: 'com.example.convoChat',
  );
}
